[build-system]
requires = ["setuptools >= 40.6.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "invest_gcm_downscaling"
description = "An InVEST plugin for the GCM Downscaling model, which downscales gridded precipitation data from CMIP6 General Circulation Models."
readme = "README.md"
version = "1.0.0"
license = "Apache-2.0"
license-files = ["LICENSE"]
maintainers = [
    {name = "Natural Capital Alliance Software Team"}
]
dependencies = [
    "taskgraph",
    "pygeoprocessing",
    "natcap.invest>=3.18.0",
    "knn @ git+https://github.com/natcap/gcm-downscaling.git"] 

[project.urls]
Repository = "https://github.com/natcap/invest-gcm-downscaling.git"
Issues = "https://github.com/natcap/invest-gcm-downscaling/issues"
Documentation = "https://github.com/natcap/invest-gcm-downscaling/blob/main/README.md"

[tool.natcap.invest]
api_version = "v1"
package_name = "invest_gcm_downscaling"
conda_dependencies = [
    "affine",
    "dask",
    "gcsfs",
    "gdal",
    "google-auth",
    "ipython",
    "jupyter",
    "matplotlib",
    "natcap.invest>=3.18.0",
    "netCDF4",
    "numpy",
    "pandas",
    "pint",
    "pyextremes",
    "pygeoprocessing",
    "pytest",
    "python",
    "rasterio",
    "rechunker",
    "scipy",
    "seaborn",
    "xarray",
    "zarr",
    "taskgraph"
]
